import { Button, MantineProvider, Text } from "@mantine/core";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { House, SpotifyLogo, MagnifyingGlass, Books } from "phosphor-react";
import { useRouter } from "next/router";
import Link from "next/link";
import Navigation from "../components/Navigation";
import HomePage from "./home";
import SearchPage from "./search";
import ReactPlayer from "react-player";
import { Fragment, useContext, useEffect, useState } from "react";
import SpotifyProvider, {
  PlayerMutedContext,
  PlayerPlayingContext,
} from "../pages/_app";
import { useForceUpdate } from "@mantine/hooks";
const Home: NextPage = () => {
  const { isPlayerPlaying, setIsPlayerPlaying } =
    useContext(PlayerPlayingContext);
  const [audioPlaying, setAudioPlaying] = useState(isPlayerPlaying);
  const router = useRouter();
  const forceUpdate = useForceUpdate();

  useEffect(() => {
    setAudioPlaying(!isPlayerPlaying);
    forceUpdate();
  }, [isPlayerPlaying]);

  return (
    <div>
      <Head>
        <title>Spotifake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MantineProvider
        withGlobalStyles
        withNormalizeCSS
        theme={{
          /** Put your mantine theme override here */
          colorScheme: "dark",
        }}
      >
        <div style={{ height: "auto", width: "100%", display: "flex" }}>
          <Link href="/">
            <Fragment>
              <HomePage />
            </Fragment>
          </Link>
        </div>
      </MantineProvider>
    </div>
  );
};

export default Home;
